INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 21:19:58] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 21:32:59] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 55, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 48, in _add_user
    result = user_tb.select("username",msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 126, in select
    cursor = super(User, self).select(*args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 98, in select
    return super(Table, self).select([self.table_name], *args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 47, in select
    return self.read(query, subs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 36, in read
    cursor.execute(query, list(values))
OperationalError: near " ": syntax error
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:36:58] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 56, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 48, in _add_user
    result = user_tb.select("username",msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 126, in select
    cursor = super(User, self).select(*args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 98, in select
    return super(Table, self).select([self.table_name], *args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 47, in select
    return self.read(query, subs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 36, in read
    cursor.execute(query, list(values))
OperationalError: near " ": syntax error
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:37:57] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 57, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 49, in _add_user
    result = user_tb.select("username",msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 126, in select
    cursor = super(User, self).select(*args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 98, in select
    return super(Table, self).select([self.table_name], *args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 47, in select
    return self.read(query, subs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 36, in read
    cursor.execute(query, list(values))
OperationalError: near " ": syntax error
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:38:27] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 57, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 49, in _add_user
    result = user_tb.select("username",msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 127, in select
    cursor = super(User, self).select(*args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 99, in select
    return super(Table, self).select([self.table_name], *args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 48, in select
    return self.read(query, subs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 36, in read
    cursor.execute(query, list(values))
OperationalError: near " ": syntax error
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:39:31] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 57, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 49, in _add_user
    result = user_tb.select("*")
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 127, in select
    cursor = super(User, self).select(*args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 99, in select
    return super(Table, self).select([self.table_name], *args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 48, in select
    return self.read(query, subs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 36, in read
    cursor.execute(query, list(values))
OperationalError: near " ": syntax error
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:41:21] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 57, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 49, in _add_user
    result = user_tb.select("*",{'username': msg['FromUserName']})
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 127, in select
    cursor = super(User, self).select(*args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 99, in select
    return super(Table, self).select([self.table_name], *args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 42, in select
    vals = ','.join([l for l in args])
TypeError: sequence item 1: expected string, dict found
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:44:51] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 57, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 52, in _add_user
    user_tb.free()
TypeError: free() takes exactly 2 arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:48:24] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:48:56] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:49:09] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:49:28] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:49:37] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:50:05] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:50:10] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:55:14] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 57, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 51, in _add_user
    user_tb.insert([msg['FromUserName'],'aaa'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 134, in insert
    self.free(super(User, self).insert(*args))
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 106, in insert
    return super(Table, self).insert(self.table_name, *args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 60, in insert
    return self.write(query, args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 27, in write
    cursor.execute(query, list(values))
OperationalError: table users has 2 columns but 1 values were supplied
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:55:43] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:56:52] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:57:09] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:57:16] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:57:42] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:58:00] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:58:11] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:58:57] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:59:08] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 22:59:55] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:01:28] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:02:43] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 58, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 52, in _add_user
    user_tb.update('createtime',username=msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 138, in update
    self.free(super(User, self).update(set_args, **kwargs))
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 110, in update
    return super(Table, self).update(self.table_name, set_args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 65, in update
    vals = [set_args[k] for k in set_args]
TypeError: string indices must be integers, not str
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:07:36] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 58, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 52, in _add_user
    user_tb.update('1',username=msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 138, in update
    self.free(super(User, self).update(set_args, **kwargs))
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 110, in update
    return super(Table, self).update(self.table_name, set_args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 65, in update
    vals = [set_args[k] for k in set_args]
TypeError: string indices must be integers, not str
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:08:36] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 58, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 52, in _add_user
    user_tb.update(1,username=msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 138, in update
    self.free(super(User, self).update(set_args, **kwargs))
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 110, in update
    return super(Table, self).update(self.table_name, set_args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 63, in update
    updates = ','.join(['%s=?' % k for k in set_args])
TypeError: 'int' object is not iterable
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:09:03] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xuqi/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/app.py", line 28, in wechat
    return api.response_msg(request)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 58, in response_msg
    self._add_user(msg)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/wechatAPI.py", line 52, in _add_user
    user_tb.update([1],username=msg['FromUserName'])
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 138, in update
    self.free(super(User, self).update(set_args, **kwargs))
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 110, in update
    return super(Table, self).update(self.table_name, set_args, **kwargs)
  File "/Users/xuqi/Documents/proj/03.ubuntu_Server/weixin/dbhelper.py", line 65, in update
    vals = [set_args[k] for k in set_args]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:09:24] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:11:19] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:12:37] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:12:48] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Oct/2016 23:13:01] "POST / HTTP/1.1" 200 -
